<a href="https://colab.research.google.com/github/CODINGHARI123/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np
numpy.__version__

'1.25.2'

# Array Initialization -Single Dimension

In [ ]:
# Numpy Array Program
# Initialization of Array
a=np.array([7,9,9,2])
print(a)

[7 9 9 2]


# Array Initialization -Multi Dimension

In [ ]:
b=np.array([(7,7,8,8),(9,9,9,10),(11,12,13,10)])
print(b)

[[ 7  7  8  8]
 [ 9  9  9 10]
 [11 12 13 10]]


# Generating Array

In [ ]:
c=np.arange(1,10,2) # range of values in array
d=np.linspace(1,5,6)# set of values by interval [start,end,no.of valuesEqaulInterva]
print(c)
print(d)

[1 3 5 7 9]
[1.  1.8 2.6 3.4 4.2 5. ]


# Array Properties

In [ ]:
a=np.array([7,9,9,2])
b=np.array([(7,9,9,10),(11,12,13,14)])
print("Dimension of Array_1:-",a.ndim)#Dimension of Array
print("Dimension of Array_2:-",b.ndim)
print("Shape of Array_1:-",a.shape)#Shape of Array
print("Shape of Array_2:-",b.shape)
print("Data Type of Array_1:-",a.dtype)#Data Type of Array
print("Data Type of Array_2:-",b.dtype)
print("Size of Array_1:-",a.size)#Size of Array
print("Size of Array_2:-",b.size)

Dimension of Array_1:- 1
Dimension of Array_2:- 2
Shape of Array_1:- (4,)
Shape of Array_2:- (2, 4)
Data Type of Array_1:- int64
Data Type of Array_2:- int64
Size of Array_1:- 4
Size of Array_2:- 8


# Array Reshape

In [ ]:
b=np.array([(7,9,9,10),(11,12,13,14)])
print(b)
b=b.reshape(4,2) # Changing rows and columns
print(b)

[[ 7  9  9 10]
 [11 12 13 14]]
[[ 7  9]
 [ 9 10]
 [11 12]
 [13 14]]


# Array Slicing

In [ ]:
b=np.array([(7,9,11,10),(11,12,13,14)])
print(b[0,2])# Slicing the Elements from certain row and column b[row_index,col_index]
print(b[0:,2]) # Slicing Elements from all rows and certain column.

11
[11 13]


# Array Value Operation

In [ ]:
e=np.array([(71,91,112,101,111,121,131,141)])
print("Minimum value in array :- ",e.min())# Minimum value in array
print("Maximum value in array:-",e.max())# Maximum value in array
print("Sum of all elements in array:-",e.sum())# Sum of all elements in array
print("Mean of all elements in array:-",e.mean())# Mean of all elements in array
print("Standard Deviation of all elements in array:-",e.std())# Standard Deviation of all elements in array

Minimum value in array :-  71
Maximum value in array:- 141
Sum of all elements in array:- 879
Mean of all elements in array:- 109.875
Standard Deviation of all elements in array:- 20.889216715808182


# Array Arithmetic Operation

In [ ]:
a=np.array([7,8,9,10])
b=np.array([11,12,13,14])
print("Addition of Array:-",a+b)
print("Subtraction of Array:-",a-b)
print("Multiplication of Array:-",a*b)
print("Division of Array:-",a/b)

Addition of Array:- [18 20 22 24]
Subtraction of Array:- [-4 -4 -4 -4]
Multiplication of Array:- [ 77  96 117 140]
Division of Array:- [0.63636364 0.66666667 0.69230769 0.71428571]


In [ ]:
a=np.array([7,8,9,10])
b=np.array([(11,12,13,14),(16,11,9,10)])
print("Sum of all elements in each column:-",b.sum(axis=0))# Sum of all elements in each column
print("Sum of all elements in each row:-",b.sum(axis=1))#Sum of all elements in each row
print("Squareroot of array elements:-",np.sqrt(a))# Squareroot of array elements
print("Standard Deviation of array:-",np.std(a))# Standard Deviation of array
print("Exponential of array elements:-",np.exp(a))# Exponential of array elements
print("Natural Log:-",np.log(a))# Natural Log
print("Log base 10:-",np.log10(a))# Log base 10

Sum of all elements in each column:- [27 23 22 24]
Sum of all elements in each row:- [50 46]
Squareroot of array elements:- [2.64575131 2.82842712 3.         3.16227766]
Standard Deviation of array:- 1.118033988749895
Exponential of array elements:- [ 1096.63315843  2980.95798704  8103.08392758 22026.46579481]
Natural Log:- [1.94591015 2.07944154 2.19722458 2.30258509]
Log base 10:- [0.84509804 0.90308999 0.95424251 1.        ]


In [ ]:
b=np.array([(7,9,11,10),(11,12,13,14)])
f=np.array([(1,2,3,4),(5,6,7,8)])
print("Vertical Stack:-",np.vstack((b,f)))#Vertical Stack
print("Horizontal Stack:-",np.hstack((b,f)))#Horizontal Stack
print("Merging as Single B:-",b.ravel())# Merging as Single
print("Merging as Single F:-",f.ravel())# Merging as Single

Vertical Stack:- [[ 7  9 11 10]
 [11 12 13 14]
 [ 1  2  3  4]
 [ 5  6  7  8]]
Horizontal Stack:- [[ 7  9 11 10  1  2  3  4]
 [11 12 13 14  5  6  7  8]]
Merging as Single B:- [ 7  9 11 10 11 12 13 14]
Merging as Single F:- [1 2 3 4 5 6 7 8]
